image: registry.soft-fx.lv/org/nodejs/node:18.5.0-alpine3.16-build

variables:
  GIT_SSL_NO_VERIFY: 1

build:
  stage: build
  script:
    - npm install && npm run build
    - pwd && ls -lah && ls -lah ./public && ls -lah ./build
    - s3cmd --host=${AWS_S3_HOST} --host-bucket=${CI_PROJECT_NAME}.${AWS_S3_HOST}
      --include=*
      --signature-v2 --progress --no-preserve --recursive --force --acl-public --no-check-certificate --delete-removed --no-mime-magic --guess-mime-type
      sync ./build/
      s3://${CI_PROJECT_NAME}/${CI_COMMIT_REF_NAME}/
